# Generated by Django 2.2 on 2021-03-18 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviewapi', '0002_auto_20210317_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interviewee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
